# Basic LAMP stack

version: "2.1"

services:
  # Web
  web:
    extends:
      file: ${HOME}/.docksal/stacks/services.yml
      service: web
    depends_on:
      - cli
    environment:
      - APACHE_FILE_PROXY
    volumes:
      - ${PROJECT_ROOT}/.docksal/etc/apache/host.conf:/usr/local/apache2/conf/extra/includes/host.conf:ro

  # DB
  db:
    extends:
      file: ${HOME}/.docksal/stacks/services.yml
      service: db

  # CLI
  cli:
    extends:
      file: ${HOME}/.docksal/stacks/services.yml
      service: cli
    environment:
      - PANTHEON_SITE
      - PANTHEON_ENV
      - TERMINUS_EMAIL
      - TERMINUS_TOKEN
      - VIRTUAL_HOST
    volumes:
      - ${PROJECT_ROOT}/.docksal/etc/drush:/etc/drush:ro
      - ${PROJECT_ROOT}/.docksal/etc/wordpress:/home/docker/.wp-cli:ro

  # Redis
  redis:
    hostname: redis
    image: ${REDIS_IMAGE:-redis:2.8}
    volumes:
      - ${PROJECT_ROOT}/.docksal/etc/redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    dns:
      - ${DOCKSAL_DNS1}
      - ${DOCKSAL_DNS2}

  # Varnish
  varnish:
    extends:
      file: ${HOME}/.docksal/stacks/services.yml
      service: varnish

  # Memcached
  memcached:
    extends:
      file: ${HOME}/.docksal/stacks/services.yml
      service: memcached

  # Solr
  solr:
    extends:
      file: ${HOME}/.docksal/stacks/services.yml
      service: solr
    volumes:
      - ${PROJECT_ROOT}/.docksal/etc/solr/conf:/var/lib/solr/conf:ro

  # Mailhog
  mail:
    hostname: mail
    image: mailhog/mailhog
    expose:
      - "80"
    environment:
      - MH_API_BIND_ADDR=0.0.0.0:80
      - MH_UI_BIND_ADDR=0.0.0.0:80
    labels:
      - io.docksal.virtual-host=webmail.${VIRTUAL_HOST}
    user: root
