#!/usr/bin/env bash

## Initialize stack and site (full reset)
##
## Usage: fin init

# Abort if anything fails
set -e

#-------------------------- Helper functions --------------------------------

SOURCE="${BASH_SOURCE[0]}"
DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
. $DIR/helper_functions

# Convert version string like 1.2.3 to integer for comparison
# param $1 version string of 3 components max (e.g. 1.10.3)
# TODO: remove this once minimal version compatibility checking for commands is implemented in fin
ver_to_int ()
{
	local leading_zeros=$(printf "%03d%03d%03d" $(echo "$1" | tr -d '[:alpha:]' | tr -d '-' | tr '.' ' '))
	# Remove leading zeroes because otherwise bash tried to handle the number as octal which leads to errors if version contains 9
	echo "$leading_zeros" | sed "s/^0*//"
}

#-------------------------- Execution --------------------------------

if [ "${FRAMEWORK}" != "d7" ] && [ "${FRAMEWORK}" != 'd8' ] && [ "${FRAMEWORK}" != 'wp' ]; then
  echo-red "FRAMEWORK variable should be set in docksal.env file before continuing."
	echo-yellow "Examples:"
	echo-yellow "FRAMEWORK=d7 	# Drupal 7"
	echo-yellow "FRAMEWORK=d8 	# Drupal 8"
	echo-yellow "FRAMEWORK=wp		# Wordpress"
  exit 1
fi

# Minimum Docksal/Fin version requirement
# TODO: this should be eventually moved to fin and version requirement defined like `#: fin_minimal_version = 1.22.0`
# in the file header
fin_minimal_version="1.22.0"
if [[ $(ver_to_int $(fin -v)) < $(ver_to_int "$fin_minimal_version") ]]; then
	echo-red "Minimal fin version required is: $fin_minimal_version"
	echo -e "Please run ${yellow}fin update${NC} and try again"
	exit 1
fi

# Stack initialization
echo -e "${green_bg} Step 1 ${NC}${green} Initializing stack...${NC}"
if [[ $DOCKER_RUNNING == "true" ]]; then
	fin reset -f
else
	fin up
fi
echo "Waiting 10s for MySQL to initialize...";
sleep 10

# Site initialization
echo -e "${green_bg} Step 2 ${NC}${green} Initializing site...${NC}"

CMD=${1:-install}

fin init-site $CMD

echo -en "${green_bg} DONE! ${NC} "
echo -e "Open ${yellow}http://${VIRTUAL_HOST}${NC} in your browser to verify the setup."
