#!/usr/bin/env bash

#: exec_target = cli

## Initialize/reinstall site
##
## Usage: fin init-site

# Abort if anything fails
set -e

#-------------------------- Settings --------------------------------

ENVIRONMENT=$1
# PROJECT_ROOT and DOCROOT are set as env variables in cli
SITE_DIRECTORY="default"
DOCROOT_PATH="${PROJECT_ROOT}/${DOCROOT}"
SITEDIR_PATH="${DOCROOT_PATH}/sites/${SITE_DIRECTORY}"

#-------------------------- END: Settings --------------------------------

#-------------------------- Helper functions --------------------------------

# Copy a settings file.
# Skips if the destination file already exists.
# @param $1 source file
# @param $2 destination file
copy_settings_file()
{
	local source="$1"
	local dest="$2"

	if [[ ! -f $dest ]]; then
		echo "Copying ${dest}..."
		cp $source $dest
	else
		echo "${dest} already in place."
	fi
}

#-------------------------- END: Helper functions --------------------------------

#-------------------------- Functions --------------------------------

# Initialize local settings files
init_settings ()
{
  if [ ${FRAMEWORK} ==  'd7' ] || [ ${FRAMEWORK} == 'd8' ]; then
	 # Copy from settings templates
	 copy_settings_file "/var/www/.docksal/etc/framework/drupal/settings.php" "${SITEDIR_PATH}/settings.php"
  elif [ ${FRAMEWORK} == 'wp' ]; then
    copy_settings_file "/var/www/.docksal/etc/framework/wordpress/wp-config.php" "${DOCROOT_PATH}/wp-config.php"
  fi
}

# Fix file/folder permissions
fix_permissions ()
{
	echo "Making site directory writable..."
  mkdir -p "${SITEDIR_PATH}/files/private"
	chmod 755 "${SITEDIR_PATH}"
	chmod 755 "${SITEDIR_PATH}/files/private"
}

#-------------------------- END: Functions --------------------------------

#-------------------------- Execution --------------------------------

mkdir ~/tmp
chmod 755 ~/tmp
sudo localedef -i en_US -f UTF-8 en_US.UTF-8

fix_permissions
# Project initialization steps
if [ $PANTHEON_ENABLE = 1 ]; then
  /var/www/.docksal/commands/terminus install
else

fi

init_settings

/var/www/.docksal/commands/refresh
#-------------------------- END: Execution --------------------------------
